//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASisImp.ServicioJavaParque {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Service.SisImp/", ConfigurationName="ServicioJavaParque.DatConService")]
    public interface DatConService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.SisImp/DatConService/setClientesRequest", ReplyAction="http://Service.SisImp/DatConService/setClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WASisImp.ServicioJavaParque.setClientesResponse setClientes(WASisImp.ServicioJavaParque.setClientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.SisImp/DatConService/setContratosRequest", ReplyAction="http://Service.SisImp/DatConService/setContratosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WASisImp.ServicioJavaParque.setContratosResponse setContratos(WASisImp.ServicioJavaParque.setContratosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.SisImp/DatConService/setCuotasRequest", ReplyAction="http://Service.SisImp/DatConService/setCuotasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WASisImp.ServicioJavaParque.setCuotasResponse setCuotas(WASisImp.ServicioJavaParque.setCuotasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.SisImp/DatConService/getDatosContratoRequest", ReplyAction="http://Service.SisImp/DatConService/getDatosContratoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WASisImp.ServicioJavaParque.getDatosContratoResponse getDatosContrato(WASisImp.ServicioJavaParque.getDatosContratoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.SisImp/DatConService/getClientesXDniRequest", ReplyAction="http://Service.SisImp/DatConService/getClientesXDniResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WASisImp.ServicioJavaParque.getClientesXDniResponse getClientesXDni(WASisImp.ServicioJavaParque.getClientesXDniRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service.SisImp/DatConService/getCuotasXContratoRequest", ReplyAction="http://Service.SisImp/DatConService/getCuotasXContratoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WASisImp.ServicioJavaParque.getCuotasXContratoResponse getCuotasXContrato(WASisImp.ServicioJavaParque.getCuotasXContratoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClientes", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class setClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        public setClientesRequest() {
        }
        
        public setClientesRequest(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setClientesResponse", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class setClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setClientesResponse() {
        }
        
        public setClientesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setContratos", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class setContratosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg7;
        
        public setContratosRequest() {
        }
        
        public setContratosRequest(int arg0, string arg1, string arg2, string arg3, double arg4, int arg5, int arg6, string arg7) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setContratosResponse", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class setContratosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setContratosResponse() {
        }
        
        public setContratosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCuotas", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class setCuotasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public setCuotasRequest() {
        }
        
        public setCuotasRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCuotasResponse", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class setCuotasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setCuotasResponse() {
        }
        
        public setCuotasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service.SisImp/")]
    public partial class datCon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int can_CuotasField;
        
        private int cod_ClienteField;
        
        private int cod_ContratoField;
        
        private int cod_EmpleadoField;
        
        private string est_ContratoField;
        
        private string fch_ContratoField;
        
        private string fch_VencimientoField;
        
        private double mon_CuotaField;
        
        private string tip_MonedaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int can_Cuotas {
            get {
                return this.can_CuotasField;
            }
            set {
                this.can_CuotasField = value;
                this.RaisePropertyChanged("can_Cuotas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cod_Cliente {
            get {
                return this.cod_ClienteField;
            }
            set {
                this.cod_ClienteField = value;
                this.RaisePropertyChanged("cod_Cliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cod_Contrato {
            get {
                return this.cod_ContratoField;
            }
            set {
                this.cod_ContratoField = value;
                this.RaisePropertyChanged("cod_Contrato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int cod_Empleado {
            get {
                return this.cod_EmpleadoField;
            }
            set {
                this.cod_EmpleadoField = value;
                this.RaisePropertyChanged("cod_Empleado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string est_Contrato {
            get {
                return this.est_ContratoField;
            }
            set {
                this.est_ContratoField = value;
                this.RaisePropertyChanged("est_Contrato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fch_Contrato {
            get {
                return this.fch_ContratoField;
            }
            set {
                this.fch_ContratoField = value;
                this.RaisePropertyChanged("fch_Contrato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fch_Vencimiento {
            get {
                return this.fch_VencimientoField;
            }
            set {
                this.fch_VencimientoField = value;
                this.RaisePropertyChanged("fch_Vencimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double mon_Cuota {
            get {
                return this.mon_CuotaField;
            }
            set {
                this.mon_CuotaField = value;
                this.RaisePropertyChanged("mon_Cuota");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tip_Moneda {
            get {
                return this.tip_MonedaField;
            }
            set {
                this.tip_MonedaField = value;
                this.RaisePropertyChanged("tip_Moneda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service.SisImp/")]
    public partial class cuota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cod_comprobanteField;
        
        private int cod_contratoField;
        
        private int cod_cuotaField;
        
        private string est_cuotaField;
        
        private string fch_cuotaField;
        
        private string fch_pagoField;
        
        private string fch_vencimientoField;
        
        private int nro_cuotaField;
        
        private double saldoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cod_comprobante {
            get {
                return this.cod_comprobanteField;
            }
            set {
                this.cod_comprobanteField = value;
                this.RaisePropertyChanged("cod_comprobante");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cod_contrato {
            get {
                return this.cod_contratoField;
            }
            set {
                this.cod_contratoField = value;
                this.RaisePropertyChanged("cod_contrato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cod_cuota {
            get {
                return this.cod_cuotaField;
            }
            set {
                this.cod_cuotaField = value;
                this.RaisePropertyChanged("cod_cuota");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string est_cuota {
            get {
                return this.est_cuotaField;
            }
            set {
                this.est_cuotaField = value;
                this.RaisePropertyChanged("est_cuota");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fch_cuota {
            get {
                return this.fch_cuotaField;
            }
            set {
                this.fch_cuotaField = value;
                this.RaisePropertyChanged("fch_cuota");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fch_pago {
            get {
                return this.fch_pagoField;
            }
            set {
                this.fch_pagoField = value;
                this.RaisePropertyChanged("fch_pago");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fch_vencimiento {
            get {
                return this.fch_vencimientoField;
            }
            set {
                this.fch_vencimientoField = value;
                this.RaisePropertyChanged("fch_vencimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int nro_cuota {
            get {
                return this.nro_cuotaField;
            }
            set {
                this.nro_cuotaField = value;
                this.RaisePropertyChanged("nro_cuota");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("saldo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service.SisImp/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ape_MaternoField;
        
        private string ape_PaternoField;
        
        private string cli_CorreoField;
        
        private int cod_ClienteField;
        
        private string nom_ClienteField;
        
        private string nom_DireccionField;
        
        private string nom_DistritoField;
        
        private string nro_DocumentoField;
        
        private string num_TelefonoField;
        
        private string tip_DocumentoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ape_Materno {
            get {
                return this.ape_MaternoField;
            }
            set {
                this.ape_MaternoField = value;
                this.RaisePropertyChanged("ape_Materno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ape_Paterno {
            get {
                return this.ape_PaternoField;
            }
            set {
                this.ape_PaternoField = value;
                this.RaisePropertyChanged("ape_Paterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cli_Correo {
            get {
                return this.cli_CorreoField;
            }
            set {
                this.cli_CorreoField = value;
                this.RaisePropertyChanged("cli_Correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int cod_Cliente {
            get {
                return this.cod_ClienteField;
            }
            set {
                this.cod_ClienteField = value;
                this.RaisePropertyChanged("cod_Cliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nom_Cliente {
            get {
                return this.nom_ClienteField;
            }
            set {
                this.nom_ClienteField = value;
                this.RaisePropertyChanged("nom_Cliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nom_Direccion {
            get {
                return this.nom_DireccionField;
            }
            set {
                this.nom_DireccionField = value;
                this.RaisePropertyChanged("nom_Direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nom_Distrito {
            get {
                return this.nom_DistritoField;
            }
            set {
                this.nom_DistritoField = value;
                this.RaisePropertyChanged("nom_Distrito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nro_Documento {
            get {
                return this.nro_DocumentoField;
            }
            set {
                this.nro_DocumentoField = value;
                this.RaisePropertyChanged("nro_Documento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string num_Telefono {
            get {
                return this.num_TelefonoField;
            }
            set {
                this.num_TelefonoField = value;
                this.RaisePropertyChanged("num_Telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string tip_Documento {
            get {
                return this.tip_DocumentoField;
            }
            set {
                this.tip_DocumentoField = value;
                this.RaisePropertyChanged("tip_Documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatosContrato", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class getDatosContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getDatosContratoRequest() {
        }
        
        public getDatosContratoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDatosContratoResponse", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class getDatosContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WASisImp.ServicioJavaParque.datCon[] @return;
        
        public getDatosContratoResponse() {
        }
        
        public getDatosContratoResponse(WASisImp.ServicioJavaParque.datCon[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientesXDni", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class getClientesXDniRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getClientesXDniRequest() {
        }
        
        public getClientesXDniRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientesXDniResponse", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class getClientesXDniResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WASisImp.ServicioJavaParque.cliente[] @return;
        
        public getClientesXDniResponse() {
        }
        
        public getClientesXDniResponse(WASisImp.ServicioJavaParque.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCuotasXContrato", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class getCuotasXContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCuotasXContratoRequest() {
        }
        
        public getCuotasXContratoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCuotasXContratoResponse", WrapperNamespace="http://Service.SisImp/", IsWrapped=true)]
    public partial class getCuotasXContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service.SisImp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WASisImp.ServicioJavaParque.cuota[] @return;
        
        public getCuotasXContratoResponse() {
        }
        
        public getCuotasXContratoResponse(WASisImp.ServicioJavaParque.cuota[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatConServiceChannel : WASisImp.ServicioJavaParque.DatConService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatConServiceClient : System.ServiceModel.ClientBase<WASisImp.ServicioJavaParque.DatConService>, WASisImp.ServicioJavaParque.DatConService {
        
        public DatConServiceClient() {
        }
        
        public DatConServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatConServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatConServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatConServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WASisImp.ServicioJavaParque.setClientesResponse WASisImp.ServicioJavaParque.DatConService.setClientes(WASisImp.ServicioJavaParque.setClientesRequest request) {
            return base.Channel.setClientes(request);
        }
        
        public int setClientes(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8) {
            WASisImp.ServicioJavaParque.setClientesRequest inValue = new WASisImp.ServicioJavaParque.setClientesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            WASisImp.ServicioJavaParque.setClientesResponse retVal = ((WASisImp.ServicioJavaParque.DatConService)(this)).setClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WASisImp.ServicioJavaParque.setContratosResponse WASisImp.ServicioJavaParque.DatConService.setContratos(WASisImp.ServicioJavaParque.setContratosRequest request) {
            return base.Channel.setContratos(request);
        }
        
        public int setContratos(int arg0, string arg1, string arg2, string arg3, double arg4, int arg5, int arg6, string arg7) {
            WASisImp.ServicioJavaParque.setContratosRequest inValue = new WASisImp.ServicioJavaParque.setContratosRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            WASisImp.ServicioJavaParque.setContratosResponse retVal = ((WASisImp.ServicioJavaParque.DatConService)(this)).setContratos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WASisImp.ServicioJavaParque.setCuotasResponse WASisImp.ServicioJavaParque.DatConService.setCuotas(WASisImp.ServicioJavaParque.setCuotasRequest request) {
            return base.Channel.setCuotas(request);
        }
        
        public int setCuotas(int arg0, int arg1) {
            WASisImp.ServicioJavaParque.setCuotasRequest inValue = new WASisImp.ServicioJavaParque.setCuotasRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WASisImp.ServicioJavaParque.setCuotasResponse retVal = ((WASisImp.ServicioJavaParque.DatConService)(this)).setCuotas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WASisImp.ServicioJavaParque.getDatosContratoResponse WASisImp.ServicioJavaParque.DatConService.getDatosContrato(WASisImp.ServicioJavaParque.getDatosContratoRequest request) {
            return base.Channel.getDatosContrato(request);
        }
        
        public WASisImp.ServicioJavaParque.datCon[] getDatosContrato(string arg0) {
            WASisImp.ServicioJavaParque.getDatosContratoRequest inValue = new WASisImp.ServicioJavaParque.getDatosContratoRequest();
            inValue.arg0 = arg0;
            WASisImp.ServicioJavaParque.getDatosContratoResponse retVal = ((WASisImp.ServicioJavaParque.DatConService)(this)).getDatosContrato(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WASisImp.ServicioJavaParque.getClientesXDniResponse WASisImp.ServicioJavaParque.DatConService.getClientesXDni(WASisImp.ServicioJavaParque.getClientesXDniRequest request) {
            return base.Channel.getClientesXDni(request);
        }
        
        public WASisImp.ServicioJavaParque.cliente[] getClientesXDni(string arg0) {
            WASisImp.ServicioJavaParque.getClientesXDniRequest inValue = new WASisImp.ServicioJavaParque.getClientesXDniRequest();
            inValue.arg0 = arg0;
            WASisImp.ServicioJavaParque.getClientesXDniResponse retVal = ((WASisImp.ServicioJavaParque.DatConService)(this)).getClientesXDni(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WASisImp.ServicioJavaParque.getCuotasXContratoResponse WASisImp.ServicioJavaParque.DatConService.getCuotasXContrato(WASisImp.ServicioJavaParque.getCuotasXContratoRequest request) {
            return base.Channel.getCuotasXContrato(request);
        }
        
        public WASisImp.ServicioJavaParque.cuota[] getCuotasXContrato(int arg0) {
            WASisImp.ServicioJavaParque.getCuotasXContratoRequest inValue = new WASisImp.ServicioJavaParque.getCuotasXContratoRequest();
            inValue.arg0 = arg0;
            WASisImp.ServicioJavaParque.getCuotasXContratoResponse retVal = ((WASisImp.ServicioJavaParque.DatConService)(this)).getCuotasXContrato(inValue);
            return retVal.@return;
        }
    }
}
